export const AUTH_HOUSE = 'AUTH_HOUSE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_USER = 'AUTH_USER'
export const CLEAR_TIMEOUT = 'CLEAR_TIMEOUT'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const START_TIMER = 'START_TIMER'